EXPERIMENT_NAME: 'eval-md4allDDa-wo-daytime-norm-80m-nuscenes-val'

SYSTEM:
  BENCHMARK: False

LOAD:
  CHECKPOINT_PATH: 'checkpoints/md4allDDa_nuscenes.ckpt'

DATASET:
  DATAROOT: 'datasets/nuScenes'

EVALUATION:
  BATCH_SIZE: 1
  SAVE:
    QUANTITATIVE_RES_PATH: 'results/quantitative/nuscenes/val/md4allDDa'
    RGB: False
    DEPTH:
      GT: False

LOSS:
  PHOTOMETRIC:
    WEIGHT: 0.0
  SMOOTHNESS_WEIGHT: 0.0
  VELOCITY_WEIGHT: 0.0
  SUPERVISED:
    WEIGHT: 1.0
