EXPERIMENT_NAME: 'eval-baseline-80m-nuscenes-val'

SYSTEM:
  BENCHMARK: False

LOAD:
  CHECKPOINT_PATH: 'md4all/checkpoints/baseline_nuscenes.ckpt'

DATASET:
  DATAROOT: 'datasets/nuscenes'

EVALUATION:
  BATCH_SIZE: 1
  SAVE:
    QUANTITATIVE_RES_PATH: 'results/quantitative/nuscenes/val'
